public class BarChartController {

    public BarChartController(CustomerActualSavingsController controller) {

    }

/*        
        //Wrapper class
        public class BarChartData {
            public String name { get; set; }
            public Double data { get; set; }
            
            public BarChartData(String name, Double data) {
                this.name = name;
                this.data = data;
            }
        }    
    }
*/
}