success__Cloudapps_Id__c,Name,success__Background_Colour__c,success__Image_URL__c,success__Type__c
SuMo-G0001,Achievement Icon,#055375,https://www.sumo-graphics.com/gallery/icons/key.png,Icon
SuMo-G0002,Achievement Watermark,#F0FAFF,https://www.sumo-graphics.com/gallery/backgrounds/key_large.png,Icon
SuMo-G0003,Challenge Icon,#035E75,https://www.sumo-graphics.com/gallery/icons/challenges.png,Icon
SuMo-G0005,Leaderboard Icon,#0081AF,https://www.sumo-graphics.com/gallery/icons/leaderboard.png,Icon
SuMo-G0007,Level Icon,#276BA1,https://www.sumo-graphics.com/gallery/icons/levels.png,Icon
SuMo-G0009,Reward (Achieved) Icon,#026C96,https://www.sumo-graphics.com/gallery/icons/rewards.png,Icon
SuMo-G0010,Reward (Generic) Icon,#0982AD,https://www.sumo-graphics.com/gallery/icons/rewards_generic.png,Icon
SuMo-G0011,Reward Watermark,#F0FAFF,https://www.sumo-graphics.com/gallery/backgrounds/awards_large.png,Icon
SuMo-G0012,Score Icon,#4995D1,https://www.sumo-graphics.com/gallery/icons/experience.png,Icon
SuMo-G0014,Competition Icon,#4995D1,https://www.sumo-graphics.com/gallery/icons/team.png,Icon
SuMo-G0015,Level-Ups,#026C96,https://www.sumo-graphics.com/gallery/icons/rocketship.png,Badge
SuMo-G0016,Account Management,#035E7F,https://www.sumo-graphics.com/gallery/icons/account_management.png,Badge
SuMo-G0017,Collaboration,#6CC4EF,https://www.sumo-graphics.com/gallery/icons/contribution.png,Badge
SuMo-G0018,Opportunity Closure,#00476D,https://www.sumo-graphics.com/gallery/icons/opportunity_closure.png,Badge
SuMo-G0019,Opportunity Management,#88C6ED,https://www.sumo-graphics.com/gallery/icons/opportunity_management.png,Badge
SuMo-G0020,Prospecting,#026EA0,https://www.sumo-graphics.com/gallery/icons/prospecting.png,Badge
SuMo-G0021,Qualification,#4995D1,https://www.sumo-graphics.com/gallery/icons/qualification.png,Badge
SuMo-G0022,Competition,#0982AD,https://www.sumo-graphics.com/gallery/icons/cup2.png,Badge
SuMo-G0100,Talk Time,#6CC4EF,https://www.sumo-graphics.com/gallery/icons/announcements.png,Badge
SuMo-G0101,Meeting Booker,#035E7F,https://www.sumo-graphics.com/gallery/icons/time_period.png,Badge
SuMo-G0102,Case Management,#88C6ED,https://www.sumo-graphics.com/gallery/icons/mailbox.png,Badge
SuMo-G0103,Call Handling,#055375,https://www.sumo-graphics.com/gallery/icons/telephone.png,Badge
SuMo-G0104,Case Comments,#026EA0,https://www.sumo-graphics.com/gallery/icons/news-paper.png,Badge
SuMo-G0105,Solution Management,#88C6ED,https://www.sumo-graphics.com/gallery/icons/style.png,Badge
SuMo-G0106,Health & Wellness,#73D0F4,https://www.sumo-graphics.com/gallery/icons/heart.png,Badge
SuMo-G0107,Charity Volunteer,#73D0F4,https://www.sumo-graphics.com/gallery/icons/brightess.png,Badge
SuMo-G0108,Training Challenge,#6CC4EF,https://www.sumo-graphics.com/gallery/icons/graduation.png,Badge
SuMo-G0109,Lead Generator,#4995D1,https://www.sumo-graphics.com/gallery/icons/prospecting.png,Badge
SuMo-G0110,Follow Up Lead,#6CC4EF,https://www.sumo-graphics.com/gallery/icons/add-to-collections.png,Badge
SuMo-G0111,User Login,#026EA0,https://www.sumo-graphics.com/gallery/icons/alarm-clock.png,Badge
SuMo-G0112,Case logger,#055375,https://www.sumo-graphics.com/gallery/icons/case.png,Badge
SuMo-G0113,Call Logger,#5BACD8,https://www.sumo-graphics.com/gallery/icons/call3.png,Badge
SuMo-G0114,Emailer,#73D0F4,https://www.sumo-graphics.com/gallery/icons/email3.png,Badge
SuMo-G0115,Training,#00476D,https://www.sumo-graphics.com/gallery/icons/diploma.png,Badge
SuMo-G0116,Web Lead,#5BACD8,https://www.sumo-graphics.com/gallery/icons/color-tv.png,Badge
SuMo-G0117,Profile Photo,#0982AD,https://www.sumo-graphics.com/gallery/icons/camera.png,Badge
SuMo-G0118,Competitive Terrain,#5BACD8,https://www.sumo-graphics.com/gallery/icons/telescope.png,Badge
SuMo-G0119,Call Management,#035E7F,https://www.sumo-graphics.com/gallery/icons/telephone.png,Badge
SuMo-G0120,Partner Engagement,#5BACD8,https://www.sumo-graphics.com/gallery/icons/opportunity_closure.png,Badge