success__Background_Colour__c,success__Type__c,Name,success__CloudApps_Id__c,success__Image_URL__c
73D0F4,Badge,Call Performance, NVM-G0003,https://www.sumo-graphics.com/gallery/icons/awards2.png
055375,Badge,Interaction Completion,NVM-G0002,https://www.sumo-graphics.com/gallery/icons/achievements.png
9CCFE8,Badge,Interaction Quality,NVM-G0001,https://www.sumo-graphics.com/gallery/icons/telephone2.png
